In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Vanes\Desktop\Kepler College\Year 2\Year 2 Term 2\Bayesian Statistices for Business\monthly_sales.csv")
df.head()

   month  sales  Unnamed: 2 Unnamed: 3  Unnamed: 4
0      1    477         NaN        NaN         NaN
1      2    420         NaN        std   95.119825
2      3    455         NaN       mean  569.388889
3      4    486         NaN        NaN         NaN
4      5    462         NaN        NaN         NaN

In [3]:
df.describe()

           month       sales  Unnamed: 2  Unnamed: 4
count  18.000000   18.000000         0.0    2.000000
mean    9.500000  569.388889         NaN  332.254357
std     5.338539   95.119825         NaN  335.358871
min     1.000000  420.000000         NaN   95.119825
25%     5.250000  483.750000         NaN  213.687091
50%     9.500000  587.000000         NaN  332.254357
75%    13.750000  641.500000         NaN  450.821623
max    18.000000  728.000000         NaN  569.388889

In [4]:
df.isnull().sum()

month          0
sales          0
Unnamed: 2    18
Unnamed: 3    16
Unnamed: 4    16
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   month       18 non-null     int64
 1   sales       18 non-null     int64
 2   Unnamed: 2  0 non-null      float64
 3   Unnamed: 3  2 non-null      str
 4   Unnamed: 4  2 non-null      float64
dtypes: float64(2), int64(2), str(1)
memory usage: 862.0 bytes

In [6]:
from sklearn.linear_model import LinearRegression

## Step 1: Fit the trend

In [7]:
X = df[['month']]
y = df[['sales']]
model = LinearRegression().fit(X,y)
df['trend'] = model.predict(X)

## Step 2: Add uncertainty

In [8]:
import pymc as pm
with pm.Model():
    slope = pm.Normal('slope', 569.38, 95.11)
    intercept = pm.Normal('intercept',569.38, 95.11)
    sigma = pm.HalfNormal('sigma', 10)
    mu = intercept + slope * X
    pm.Normal('obs', mu, sigma, observed=y)
    post = pm.sample(1000)

g++ not available, if using conda: `conda install gxx`
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [slope, intercept, sigma]

Output()

Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 16 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

## Step 3: Interpret the range

In [9]:
fc = post.posterior
pred = fc ['intercept'] + fc ['slope'] * 19
low, high = pred.quantile([0.1, 0.9])
print(f'{low:.0f} to {high: .0f} units')

714 to  746 units

In [20]:
df = pd.read_csv(r"C:\Users\Vanes\Desktop\Kepler College\Year 2\Year 2 Term 2\Bayesian Statistices for Business\momo_transactions.csv")

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   week          12 non-null     int64
 1   transactions  12 non-null     int64
dtypes: int64(2)
memory usage: 324.0 bytes

## Step 1 : Fit data

In [22]:
X = df[["week"]]
y = df[["transactions"]]
model = LinearRegression().fit(X,y)

## Step 2: add uncertain

In [23]:
with pm.Model():
    slope = pm.Normal('slope', 264.58, 49.93)
    intercept = pm.Normal('intercept', 264.58, 49.93)
    sigma = pm.HalfNormal('sigma', 10)
    mu = intercept + slope*X
    pm.Normal('obs', mu, sigma, observed=y)
    post = pm.sample(1000)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [slope, intercept, sigma]

Output()

Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 12 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

## Step 3: Interpreting range

In [24]:
fc = post.posterior
pred = fc['intercept'] + fc['slope'] * 14
low, high = pred.quantile([0.1, 0.9])
print(f'{low:.0f} to {high: .0f} transcations')

345 to  376 transcations

In [15]:
df = pd.read_csv(r"C:\Users\Vanes\Desktop\Kepler College\Year 2\Year 2 Term 2\Bayesian Statistices for Business\cafe_visits.csv")

## Step 1 : Fit data

In [17]:
X = df[["day"]]
y = df[["visits"]]
model = LinearRegression().fit(X,y)

## Step 2: add uncertain

In [18]:
with pm.Model():
    slope = pm.Normal('slope', 264.58, 49.93)
    intercept = pm.Normal('intercept', 264.58, 49.93)
    sigma = pm.HalfNormal('sigma', 10)
    mu = intercept + slope*X
    pm.Normal('obs', mu, sigma, observed=y)
    post = pm.sample(1000)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [slope, intercept, sigma]

Output()

Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

## Step 3: Interpreting range

In [19]:
fc = post.posterior
pred = fc['intercept'] + fc['slope'] * 14
low, high = pred.quantile([0.1, 0.9])
print(f'{low:.0f} to {high: .0f} visits')

75 to  81 visits

In [25]:
df = pd.read_csv(r"C:\Users\Vanes\Desktop\Kepler College\Year 2\Year 2 Term 2\Bayesian Statistices for Business\potato_prices.csv")

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   24 non-null     int64
 1   price   24 non-null     int64
dtypes: int64(2)
memory usage: 516.0 bytes

## Step 1 : Fit data

In [27]:
X = df[["month"]]
y = df[["price"]]
model = LinearRegression().fit(X,y)

## Step 2: add uncertain

In [28]:
with pm.Model():
    slope = pm.Normal('slope', 264.58, 49.93)
    intercept = pm.Normal('intercept', 264.58, 49.93)
    sigma = pm.HalfNormal('sigma', 10)
    mu = intercept + slope*X
    pm.Normal('obs', mu, sigma, observed=y)
    post = pm.sample(1000)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [slope, intercept, sigma]

Output()

Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 12 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

## Step 3: Interpreting range

In [29]:
fc = post.posterior
pred = fc['intercept'] + fc['slope'] * 14
low, high = pred.quantile([0.1, 0.9])
print(f'{low:.0f} to {high: .0f} price')

344 to  366 price